# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 393ffd148851fe4a4336432162cc479bcb497fb2c158a64d2c9d7741042a6137670d492b262adc197c7950134f4c5e79829fac73fc841d8af2ae7525a5bfe36f

test:
  secret_key_base: 9a7895d462c1e8f76639f8bf989b58932709dc3240f28cfaaf126220ac3c5d7ef54fc5c6339f9f0c8c650bc2e166182bfdfbea568b00dc5071bf8b674e7b9608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
